version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "08:00"
    open-pull-requests-limit: 5
    assignees:
      - "rabestro"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "08:00"
    open-pull-requests-limit: 5
    assignees:
      - "rabestro"
    labels:
      - "ci-cd"
    commit-message:
      prefix: "chore"
